name: Update Indexes

on:
  push:
    branches: 
      - main
    paths:
      - 'content-production/**/*.md'
      - 'foreign-lang/**/*.md'
      - 'webdev/**/*.md'
      - '.github/workflows/update-indexes.yml'

jobs:
  update-indexes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz

    - name: Update indexes
      id: update
      run: |
        python3 - <<EOF
        import os
        from datetime import datetime
        import pytz
        import re
        import subprocess
        
        def get_korean_time():
            kst = pytz.timezone('Asia/Seoul')
            now = datetime.now(kst)
            return now.strftime('%Y-%m-%d %H:%M:%S')
            
        def update_index_file(index_path, folder_path, is_foreign_lang=False):
            print(f"Processing {index_path}...")
            
            if not os.path.exists(index_path):
                print(f"Warning: {index_path} does not exist")
                return False
                
            with open(index_path, 'r', encoding='utf-8') as f:
                lines = f.readlines()
                
            new_lines = []
            updated = False
            
            if is_foreign_lang:
                for line in lines:
                    if '#### Last updated:' in line:
                        new_lines.append(f'#### Last updated: {get_korean_time()}\n')
                        updated = True
                    else:
                        new_lines.append(line)
            else:
                for line in lines:
                    if '#### Last updated:' in line:
                        new_lines.append(f'#### Last updated: {get_korean_time()}\n')
                        updated = True
                    else:
                        new_lines.append(line)
            
            if updated:
                with open(index_path, 'w', encoding='utf-8') as f:
                    f.writelines(new_lines)
                print(f"Updated {index_path}")
                return True
            return False
            
        # Get changed files first
        result = subprocess.run(['git', 'diff', '--name-only', 'HEAD^', 'HEAD'], 
                             capture_output=True, text=True)
        changed_files = result.stdout.splitlines()
        print("Changed files:", changed_files)
        
        # Set any_updates to True at the start
        any_updates = True
        
        # Then update files
        if any(f.startswith('content-production/') for f in changed_files):
            update_index_file('content-production/index.md', 'content-production')
        
        if any(f.startswith('foreign-lang/') for f in changed_files):
            update_index_file('foreign-lang/index.md', 'foreign-lang', True)
        
        if any(f.startswith('webdev/') for f in changed_files):
            update_index_file('webdev/index.md', 'webdev')
        
        # Finally update README.md
        if os.path.exists('README.md'):
            print("Updating README.md")
            with open('README.md', 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            new_lines = []
            for line in lines:
                if 'Last updated:' in line:
                    if line.startswith('####'):
                        new_lines.append(f'#### Last updated: {get_korean_time()}\n')
                    elif line.startswith('####'):
                        new_lines.append(f'#### Last updated: {get_korean_time()}\n')
                    else:
                        new_lines.append(f'#### Last updated: {get_korean_time()}\n')
                else:
                    new_lines.append(line)
            
            # Always write the file
            with open('README.md', 'w', encoding='utf-8') as f:
                f.writelines(new_lines)
            print("Updated README.md")
        
        # Exit with status code
        exit(0 if any_updates else 1)
        EOF

    - name: Check for changes
      id: changes
      run: |
        git diff --quiet || echo "::set-output name=changed::true"

    - name: Commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update indexes"
        
    - name: Push changes
      if: steps.changes.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 